language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --lib="lib/WundergroundClient" --project-conf=platformio.ini