# This is a basic workflow to help you get started with Actions

name: PlatformIO CI

# Controls when the action will run. Triggers the workflow on push to any branch
on:
  push:
    branches: [ '*' ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        
      - name: Install pio and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio 
          
      - name: Run PlatformIO
        run: pio run -e esp12e
